### ISSUE TITLE
[ENH] - General RST Dashboard Feedback 07/16

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARCOP#286]
### Which app?

Dashboards

### Describe requirements

4.	Worksite Triage Dashboard:
a.	Map changes location when you reset the top ribbon filtering by incident - this can be changed
b.	No zoom to location ability - this can be added
c.	No return to previous zoom state after refresh feature - unsure if this exists in Dashboards
d.	The above three are incorporated currently in the intel manager so that is why they were front and center for me
e.	Add a “clear all filters” button along the top to clear out all the filters top ribbon filters - this does not exist
i.	This would be very handy when filtering by areas since you need to do this one by one otherwise because you don’t know if the filters are enabled at a glance unless you go into each one

### Alternatives

None

### Priority impact

p0 - not time sensitive

### Impact

Inconvenient

**Comment by oviera-napsg** [comment]
a. Map changes location when you reset the top ribbon filtering by incident - this can be changed **_Reset of a filter or global reset Dashboard button will revert map location to where the map is saved_**
b. No zoom to location ability - this can be added **_Map setting in Dashboard_**
c. No return to previous zoom state after refresh feature - unsure if this exists in Dashboards **_No known solution within Dashboards.  Map reversions only take place when a categorical filter is cleared or when global Dashboard reset button (lower right) is clicked--in both cases it reverts to map's saved extent_**
d. The above three are incorporated currently in the intel manager so that is why they were front and center for me
e. Add a “clear all filters” button along the top to clear out all the filters top ribbon filters - this does not exist _**Ditto**_
i. This would be very handy when filtering by areas since you need to do this one by one otherwise because you don’t know if the filters are enabled at a glance unless you go into each one -- _**Add global 'Reset Dashboard' button if not there already**_

**Comment by oviera-napsg** [comment]
Response & enhancements:

a.  Each header filter has a Reset button and, if applicable, a Select All button.  There is also a global reset button on the lower right corner of the dashboard that resets the header filters, sidebar filters, and the map extent to its saved extent.
b.  Added.
c.  Not a function in dashboards.  Options for returning to a specific extent include (1) resetting the dashboard which resets the map extent to its saved extent (2) using the Find My Location feature in the map or (3) utilizing a Bookmark which involves coordination with NAPSG to have an extent saved as a Bookmark; usually only done if requested and during multiple significant responses.
d.  Limited by the functionalities built into ArcGIS Dashboards vs. ArcGIS Web App Builder and Experience Builder
e.  Does not exist in ArcGIS Dashboards; the closest thing is the reset button in the lower right corner of the Dashboard which clears the header filters, sidebar filters, and map extent.
f.  Global reset button toggled on.  There are not actions or settings within this button, it's just 'on' or 'off.'
